# Generated by Django 4.2.4 on 2023-09-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('choices', models.CharField(max_length=200)),
                ('solution', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'questions',
            },
        ),
    ]
